const TermsAndConditionsComponent = () => {
    return (
      <div className="bg-white p-6 md:p-8 max-w-3xl mx-auto rounded-lg">
        <h1 className="text-2xl font-light text-gray-800 text-center tracking-wide">Terms and Conditions</h1>
        <p className="mt-3 text-sm text-gray-600 text-center">
          Engaging with Golden Clove’s services means you accept these terms.
        </p>

        <p className="mt-2 text-sm text-gray-600">
          1. This document is an electronic record under the Information Technology Act, 2000, and its applicable rules, including amendments related to electronic records in various statutes as updated by the Information Technology Act, 2000. Generated by a computer system, it requires no physical or digital signatures.
        </p>

        <p className="mt-2 text-sm text-gray-600">
          2. This document complies with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, mandating the publication of rules, regulations, privacy policy, and Terms of Use for accessing or using the domain https://www.goldenclove.in/ (“Website”), including its related mobile site and application (hereinafter “Platform”).
        </p>

        <p className="mt-2 text-sm text-gray-600">
          3. The Platform is owned by GITANJALI PANDA, a company incorporated under the Companies Act, 1956, with its registered office at Building Sidhartha Nagar 2nd Lane, Village/Town Berhampur, Block Berhampur, Sidhartha Nagar 2nd Lane, City Berhampur, Berhampur, India (hereinafter “Platform Owner,” “we,” “us,” “our”).
        </p>

        <p className="mt-2 text-sm text-gray-600">
          4. Your use of the Platform, services, and tools is governed by these Terms of Use, including applicable policies incorporated by reference. Transacting on the Platform subjects you to its specific policies. By using the Platform, you contract with the Platform Owner, and these Terms of Use, including policies, form your binding obligations with us. These Terms relate to your use of our website, goods, or services (collectively, “Services”). Any additional or conflicting terms you propose are rejected by the Platform Owner and have no effect.
        </p>

        <p className="mt-2 text-sm text-gray-600">
          5. We may modify these Terms of Use at any time without reason. It’s your responsibility to periodically review them for updates.
        </p>

        <p className="mt-2 text-sm text-gray-600">
          6. For these Terms of Use, “you,” “your,” or “user” refers to any natural or legal person agreeing to become a user/buyer on the Platform.
        </p>

        <p className="mt-2 text-sm text-gray-600">
          7. ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL TERMS AND CONDITIONS HEREIN, SO PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
        </p>

        <p className="mt-2 text-sm text-gray-600">
          8. Using the Platform or Services is subject to the following:<br />
             - You agree to provide true, accurate, and complete information during and after registration, and you’re responsible for all actions via your registered account.<br/>
             - Neither we nor third parties guarantee the accuracy, timeliness, performance, completeness, or suitability of information and materials on this website or through Services for any purpose. You acknowledge potential inaccuracies or errors, and we exclude liability for these to the fullest extent permitted by law.<br/>
             - Your use of our Services and Platform is at your sole risk and discretion; we’re not liable. You must independently ensure the Services meet your needs.<br/>
             - The Platform’s and Services’ contents are proprietary to us or licensed to us. You have no claim to intellectual property rights, title, or interest in them, including design, layout, look, and graphics.<br/>
             - You acknowledge that unauthorized use of the Platform or Services may result in action against you per these Terms of Use or applicable laws.<br/>
             - You agree to pay the charges for availing the Services.<br/>
             - You agree not to use the Platform or Services for unlawful, illegal, or prohibited purposes under these Terms or applicable Indian or local laws.<br/>
             - You acknowledge that the website and Services may link to third-party sites, governed by their terms of use and privacy policies. These links are for convenience only.<br/>
             - Initiating a transaction for Services creates a legally binding contract with the Platform Owner.<br/>
             - You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies, and their officers, directors, agents, and employees from claims, demands, or actions—including reasonable attorney’s fees—arising from your breach of these Terms of Use, Privacy Policy, other policies, or violation of laws, rules, regulations, or third-party rights (including intellectual property).<br/>
             - Neither party is liable for failure to perform under these Terms if prevented or delayed by a force majeure event.<br/>
             - These Terms, and any related disputes or claims, are governed by and construed under the laws of India.<br/>
             - All disputes arising from these Terms are subject to the exclusive jurisdiction of courts in Berhampur, Odisha.<br/>
             - All concerns or communications about these Terms must be sent using the contact information on this website.<br/>
        </p>

        <p className="mt-5 text-sm text-gray-600 text-center">
          Need clarity? Contact <span className="font-medium">sales.goldenclove@gmail.com</span>.
        </p>
      </div>
    );
  };
  
  export default TermsAndConditionsComponent;
  